"""Model catalog: the single source of MODEL_CONFIG.

The 130 hand-authored entries live as data in `model_catalog_data.json`. The 32
`gemini_omni_*` entries stay generated by `_build_gemini_omni_entries()` — they are
a regular product of (2 video_type × 2 orientation × 4 duration × 2 upsample) and
keeping them as a factory means one parameter change touches one place, not 32.

Assembly order (base entries first, omni appended) matches the historical
`MODEL_CONFIG = {...}; MODEL_CONFIG.update(_build_gemini_omni_entries())` exactly,
which the ordered OpenAI model-list snapshot depends on.
"""
import json
from pathlib import Path
from typing import Any, Dict


_DATA_PATH = Path(__file__).parent / "model_catalog_data.json"


def _load_base_entries() -> Dict[str, Dict[str, Any]]:
    """Load the hand-authored (non-omni) model entries, preserving order."""
    with open(_DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


# ========== Gemini Omni Flash (abra) 模型注册工厂 ==========
# 32 个 entry = 2 video_type × 2 orientation × 4 duration × 2 (base/1080p upsample)
_OMNI_DURATIONS = (4, 6, 8, 10)
_OMNI_UPSAMPLE_1080P = {
    "resolution": "VIDEO_RESOLUTION_1080P",
    "model_key": "veo_3_1_upsampler_1080p",
}
_OMNI_R2V_MAX_IMAGES = 7  # 上游 Flow R2V 单次最多 7 张参考图


def _build_gemini_omni_entries() -> Dict[str, Dict[str, Any]]:
    """生成 32 个 gemini_omni_* MODEL_CONFIG entry。改参数只改这里。"""
    entries: Dict[str, Dict[str, Any]] = {}
    for video_type in ("t2v", "r2v"):
        for orientation_suffix, aspect_ratio in (
            ("", "VIDEO_ASPECT_RATIO_LANDSCAPE"),
            ("_portrait", "VIDEO_ASPECT_RATIO_PORTRAIT"),
        ):
            for duration in _OMNI_DURATIONS:
                for upsample_suffix in ("", "_1080p"):
                    key = f"gemini_omni_{video_type}{orientation_suffix}_{duration}s{upsample_suffix}"
                    entry: Dict[str, Any] = {
                        "type": "video",
                        "video_type": video_type,
                        "model_key": f"abra_{video_type}_{duration}s",
                        "aspect_ratio": aspect_ratio,
                        "supports_images": (video_type == "r2v"),
                        "use_v2_model_config": True,
                        # TIER_TWO 不能升级到 _ultra（abra 没 _ultra 变体）。
                        "allow_tier_upgrade": False,
                    }
                    if video_type == "r2v":
                        entry["min_images"] = 0
                        entry["max_images"] = _OMNI_R2V_MAX_IMAGES
                    if upsample_suffix == "_1080p":
                        entry["upsample"] = _OMNI_UPSAMPLE_1080P
                    entries[key] = entry
    return entries


def build_model_config() -> Dict[str, Dict[str, Any]]:
    """Assemble the full model catalog: base data + generated omni entries."""
    catalog = _load_base_entries()
    catalog.update(_build_gemini_omni_entries())
    return catalog


# Module-level singleton — imported as `from ..core.model_catalog import MODEL_CONFIG`.
MODEL_CONFIG: Dict[str, Dict[str, Any]] = build_model_config()
