"""Model catalog: the single source of MODEL_CONFIG.

The 128 hand-authored entries live as data in `model_catalog_data.json`. The
`gemini_omni_*` entries stay generated by `_build_gemini_omni_entries()` — they are
a regular product of (4 video_type × 2 orientation × 4 duration × 4 resolution
variant) and keeping them as a factory means one parameter change touches one
place, not 128.

Assembly order (base entries first, omni appended) matches the historical
`MODEL_CONFIG = {...}; MODEL_CONFIG.update(_build_gemini_omni_entries())` exactly,
which the ordered OpenAI model-list snapshot depends on.

Upstream ground truth (2026-08-28, captured from Flow projectInitialData on a
SERVICE_TIER_INTERMEDIATE/Pro account): the "Omni 1.1 Flash" family id is `abra`.
Per-duration keys exist for t2v/r2v/i2v at 720p and 360p (`*_360p` suffix), plus
first+last-frame keys `omni_flash_i2v_{d}s_first_last{,_360p}`. 720p→1080P uses
`veo_3_1_upsampler_1080p` (cost 0), 720p→4K uses `veo_3_1_upsampler_4k` (cost 50,
SERVICE_TIER_ADVANCED only — Pro/ENTRY get UNAVAILABLE → 403 at submit time).
"""
import json
from pathlib import Path
from typing import Any, Dict


_DATA_PATH = Path(__file__).parent / "model_catalog_data.json"


def _load_base_entries() -> Dict[str, Dict[str, Any]]:
    """Load the hand-authored (non-omni) model entries, preserving order."""
    with open(_DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


# ========== Gemini Omni Flash (abra) 模型注册工厂 ==========
# 128 个 entry = 4 video_type × 2 orientation × 4 duration × 4 分辨率变体
# (720p 原版 / 1080p 上采样 / 4K 上采样 / 360p 原生)
_OMNI_DURATIONS = (4, 6, 8, 10)
_OMNI_UPSAMPLE_1080P = {
    "resolution": "VIDEO_RESOLUTION_1080P",
    "model_key": "veo_3_1_upsampler_1080p",
}
_OMNI_UPSAMPLE_4K = {
    "resolution": "VIDEO_RESOLUTION_4K",
    "model_key": "veo_3_1_upsampler_4k",
}
_OMNI_R2V_MAX_IMAGES = 7  # 上游 Flow R2V 单次最多 7 张参考图

# video_type -> (model_key 模板, min_images, max_images)
# i2v 与 fl 都走 handler 的 i2v 分支（start/end image 端点），靠图片数量约束区分：
# i2v 仅首帧（1 张），fl 首尾帧（必须 2 张，上游 requirements 强制 START+END_IMAGE）。
_OMNI_VIDEO_TYPES = {
    "t2v": ("abra_t2v_{d}s", None, None),
    "r2v": ("abra_r2v_{d}s", 0, _OMNI_R2V_MAX_IMAGES),
    "i2v": ("abra_i2v_{d}s", 1, 1),
    "fl": ("omni_flash_i2v_{d}s_first_last", 2, 2),
}

# 分辨率变体后缀 -> 行为；720p 原版无后缀。
# "_360p" 是原生 360p 生成（model_key 加 _360p），不参与上采样链。
_OMNI_RESOLUTION_VARIANTS = ("", "_1080p", "_4k", "_360p")


def _build_gemini_omni_entries() -> Dict[str, Dict[str, Any]]:
    """生成全部 gemini_omni_* MODEL_CONFIG entry。改参数只改这里。"""
    entries: Dict[str, Dict[str, Any]] = {}
    for video_type, (key_template, min_images, max_images) in _OMNI_VIDEO_TYPES.items():
        for orientation_suffix, aspect_ratio in (
            ("", "VIDEO_ASPECT_RATIO_LANDSCAPE"),
            ("_portrait", "VIDEO_ASPECT_RATIO_PORTRAIT"),
        ):
            for duration in _OMNI_DURATIONS:
                for variant in _OMNI_RESOLUTION_VARIANTS:
                    key = f"gemini_omni_{video_type}{orientation_suffix}_{duration}s{variant}"
                    model_key = key_template.format(d=duration)
                    if variant == "_360p":
                        model_key += "_360p"
                    entry: Dict[str, Any] = {
                        "type": "video",
                        "video_type": "i2v" if video_type in ("i2v", "fl") else video_type,
                        "model_key": model_key,
                        "aspect_ratio": aspect_ratio,
                        "supports_images": max_images is not None,
                        "use_v2_model_config": True,
                        # TIER_TWO 不能升级到 _ultra（abra 没 _ultra 变体）。
                        "allow_tier_upgrade": False,
                    }
                    if min_images is not None:
                        entry["min_images"] = min_images
                    if max_images is not None:
                        entry["max_images"] = max_images
                    if variant == "_1080p":
                        entry["upsample"] = _OMNI_UPSAMPLE_1080P
                    elif variant == "_4k":
                        entry["upsample"] = _OMNI_UPSAMPLE_4K
                    entries[key] = entry

    # 视频延长/编辑（abra_edit，2026-08-29 抓包验证）。独立条目，不进上面的
    # 时长×变体乘积：输出固定 10s 720P，宽高比与帧数继承源视频（handler 轮询
    # 源媒体后覆盖 aspect_ratio）。调用契约见 generation_handler 的 edit 分支。
    entries["gemini_omni_edit"] = {
        "type": "video",
        "video_type": "edit",
        "model_key": "abra_edit",
        "aspect_ratio": "VIDEO_ASPECT_RATIO_LANDSCAPE",  # 占位，提交前被源视频覆盖
        "supports_images": False,
        "use_v2_model_config": True,
        "allow_tier_upgrade": False,
        "edit": {"resolution": "VIDEO_RESOLUTION_720P"},
    }
    return entries


def build_model_config() -> Dict[str, Dict[str, Any]]:
    """Assemble the full model catalog: base data + generated omni entries."""
    catalog = _load_base_entries()
    catalog.update(_build_gemini_omni_entries())
    return catalog


# Module-level singleton — imported as `from ..core.model_catalog import MODEL_CONFIG`.
MODEL_CONFIG: Dict[str, Dict[str, Any]] = build_model_config()
